### PR TITLE
issue/129 Part fix for branching conflict

### LINKED ISSUE #129: Conflict with adapt-contrib-branching
If a completed branching article is restored with trickle, branching does not complete the article before the trickle buttons are added and so trickle, adding an imcomplete button, prevents the article from completing as necessary. (very circular).

Effectively these lines cannot complete the article because article is not yet completed by branching:
https://github.com/adaptlearning/adapt-contrib-trickle/blob/71255c43d5c67812e1b88e6169dd524852de5497/js/TrickleButtonModel.js#L9-L15

Secondary branching issue https://github.com/adaptlearning/adapt-contrib-branching/issues/7

### PR DESCRIPTION
**Pull request by oliverfoster**
fixes #129 

### Fixed
* Pushed trickle button creation and locking initialization to the final point in the startup process after `app:dataReady` (after spoor restoration), branching and assessment and before `adapt:start`

### CODE REVIEW

**Review by cahirodoherty-learningpool — APPROVED** [review]
👀

File: js/controller.js [hunk 1]
```diff
@@ -36,8 +36,11 @@ class TrickleController extends Backbone.Controller {
 
   async onDataReady() {
     await data.whenReady();
-    addButtonComponents();
-    applyLocks();
+    Adapt.wait.for((done) => {
```
Comment (oliverfoster) [inline js/controller.js:39]: Please remove extra brackets
```suggestion
    Adapt.wait.for(done => {
```

**Review by joe-allen-89 — APPROVED** [review]

**Review by joe-allen-89 — APPROVED** [review]

**Review by tomgreenfield — APPROVED** [review]
:eye:
